language: rust
cache: cargo
rust: nightly
before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a
  - mdbook --version
script:
  - mdbook build
  - mdbook test
