language: shell

before_install:
  - curl -sSL https://sh.rustup.rs | sh -s -- -y --default-toolchain=nightly --profile=minimal -c rust-docs
  - export PATH="$HOME/.cargo/bin:$PATH"

install:
  - travis_retry curl -Lf https://github.com/rust-lang-nursery/mdBook/releases/download/v0.3.1/mdbook-v0.3.1-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=$HOME/.cargo/bin

script:
  - export PATH=$PATH:/home/travis/.cargo/bin && mdbook test
  - (cd stable-check && cargo run -- ../src)
  - tests/linkcheck.sh
