[package]
name = "rustc-std-workspace-alloc"
<<<<<<< HEAD   (086005 Importing rustc-1.38.0)
version = "1.0.0"
=======
version = "1.99.0"
>>>>>>> BRANCH (8cd2c9 Importing rustc-1.39.0)
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = 'MIT OR Apache-2.0'
description = """
Hack for the compiler's own build system
"""
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
alloc = { path = "../../liballoc" }
