[package]
authors = ["The Rust Project Developers"]
name = "rustc_mir"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_mir"
path = "lib.rs"
doctest = false

[dependencies]
arena = { path = "../libarena" }
either = "1.5.0"
dot = { path = "../libgraphviz", package = "graphviz" }
log = "0.4"
log_settings = "0.1.1"
<<<<<<< HEAD   (086005 Importing rustc-1.38.0)
polonius-engine  = "0.9.0"
=======
polonius-engine  = "0.10.0"
>>>>>>> BRANCH (8cd2c9 Importing rustc-1.39.0)
rustc = { path = "../librustc" }
rustc_target = { path = "../librustc_target" }
rustc_data_structures = { path = "../librustc_data_structures" }
rustc_errors = { path = "../librustc_errors" }
<<<<<<< HEAD   (086005 Importing rustc-1.38.0)
=======
rustc_lexer = { path = "../librustc_lexer" }
>>>>>>> BRANCH (8cd2c9 Importing rustc-1.39.0)
rustc_serialize = { path = "../libserialize", package = "serialize" }
syntax = { path = "../libsyntax" }
syntax_pos = { path = "../libsyntax_pos" }
byteorder = { version = "1.3" }
rustc_apfloat = { path = "../librustc_apfloat" }
smallvec = { version = "0.6.7", features = ["union", "may_dangle"] }
