[package]
authors = ["The Rust Project Developers"]
name = "rustc_codegen_llvm"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_codegen_llvm"
path = "lib.rs"
crate-type = ["dylib"]
test = false

[dependencies]
<<<<<<< HEAD   (086005 Importing rustc-1.38.0)
cc = "1.0.1" # Used to locate MSVC
num_cpus = "1.0"
tempfile = "3.0"
=======
>>>>>>> BRANCH (8cd2c9 Importing rustc-1.39.0)
rustc_llvm = { path = "../librustc_llvm" }

[features]
# This is used to convince Cargo to separately cache builds of `rustc_codegen_llvm`
# when this option is enabled or not. That way we can build two, cache two
# artifacts, and have nice speedy rebuilds.
emscripten = ["rustc_llvm/emscripten"]
