[package]
authors = ["The Rust Project Developers"]
name = "compiletest"
version = "0.0.0"
edition = "2018"

[dependencies]
diff = "0.1.10"
<<<<<<< HEAD   (086005 Importing rustc-1.38.0)
env_logger = { version = "0.5", default-features = false }
=======
env_logger = { version = "0.6", default-features = false }
>>>>>>> BRANCH (8cd2c9 Importing rustc-1.39.0)
getopts = "0.2"
log = "0.4"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustfix = "0.4.1"
lazy_static = "1.0"
walkdir = "2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
miow = "0.3"
winapi = { version = "0.3", features = ["winerror"] }
