[package]
name = "rls"
<<<<<<< HEAD   (086005 Importing rustc-1.38.0)
version = "1.38.0"
=======
version = "1.39.0"
>>>>>>> BRANCH (8cd2c9 Importing rustc-1.39.0)
edition = "2018"
authors = ["Nick Cameron <ncameron@mozilla.com>", "The RLS developers"]
description = "Rust Language Server - provides information about Rust programs to IDEs and other tools"
license = "Apache-2.0/MIT"
repository = "https://github.com/rust-lang/rls"
categories = ["development-tools"]

build = "build.rs"

[lib]
name = "rls"
doctest = false
path = "rls/src/lib.rs"

[[bin]]
name = "rls"
test = false
path = "rls/src/main.rs"

[dependencies]
rls-analysis = "0.18.0"
rls-data = "0.19"
# FIXME: Release rls-rustc 0.6.0 to crates.io
rls-rustc = { version = "0.6.0", path = "rls-rustc" }
rls-span = "0.5"
rls-vfs = "0.8"
<<<<<<< HEAD   (086005 Importing rustc-1.38.0)
=======
rls-ipc = { version = "0.1.0", path = "rls-ipc", optional = true }
>>>>>>> BRANCH (8cd2c9 Importing rustc-1.39.0)

<<<<<<< HEAD   (086005 Importing rustc-1.38.0)
cargo = { git = "https://github.com/rust-lang/cargo", rev = "1f74bdf4494f4d51dbe3a6af5474e39c8d194ad6" }
cargo_metadata = "0.8"
clippy_lints = { git = "https://github.com/rust-lang/rust-clippy", rev = "71be6f62fa920c0bd10cdf3a29aeb8c6719a8075", optional = true }
=======
cargo = { git = "https://github.com/rust-lang/cargo", rev = "cdf7f6380a7a23a5bffc26ab35fc434200f30ad6" }
cargo_metadata = "0.8"
clippy_lints = { git = "https://github.com/rust-lang/rust-clippy", rev = "72da1015d6d918fe1b29170acbf486d30e0c2695", optional = true }
>>>>>>> BRANCH (8cd2c9 Importing rustc-1.39.0)
env_logger = "0.6"
failure = "0.1.1"
futures = { version = "0.1", optional = true }
home = "0.5"
itertools = "0.8"
<<<<<<< HEAD   (086005 Importing rustc-1.38.0)
jsonrpc-core = "12"
lsp-types = { version = "=0.57.2", features = ["proposed"] }
=======
jsonrpc-core = "13"
lsp-types = { version = "0.60", features = ["proposed"] }
>>>>>>> BRANCH (8cd2c9 Importing rustc-1.39.0)
lazy_static = "1"
log = "0.4"
num_cpus = "1"
<<<<<<< HEAD   (086005 Importing rustc-1.38.0)
racer = { version = "2.1.25", default-features = false }
=======
racer = { version = "2.1.27", default-features = false }
>>>>>>> BRANCH (8cd2c9 Importing rustc-1.39.0)
rand = "0.6"
rayon = "1"
rustc_tools_util = "0.2"
<<<<<<< HEAD   (086005 Importing rustc-1.38.0)
rustfmt-nightly = "1.4.3"
=======
rustfmt-nightly = "1.4.8"
>>>>>>> BRANCH (8cd2c9 Importing rustc-1.39.0)
rustc-serialize = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_ignored = "0.1"
tokio = { version = "0.1", optional = true }
url = "2"
walkdir = "2"
regex = "1"
ordslice = "0.3"
crossbeam-channel = "0.3"
toml = "0.5"
heck = "0.3"

# A noop dependency that changes in the Rust repository, it's a bit of a hack.
# See the `src/tools/rustc-workspace-hack/README.md` file in `rust-lang/rust`
# for more information.
rustc-workspace-hack = "1.0.0"

[dev-dependencies]
difference = "2"
tempfile = "3"
lsp-codec = "0.1.2"
tokio = "0.1"
futures = "0.1"
tokio-process = "0.2"
tokio-timer = "0.2"

[build-dependencies]
rustc_tools_util = "0.2"

[features]
<<<<<<< HEAD   (086005 Importing rustc-1.38.0)
clippy = ["clippy_lints"]
=======
clippy = ["clippy_lints", "rls-rustc/clippy"]
ipc = ["tokio", "futures", "rls-rustc/ipc", "rls-ipc/server"]
default = []
>>>>>>> BRANCH (8cd2c9 Importing rustc-1.39.0)
